baseurl = "http://latent.club"
languageCode = "ko-kr"
title = "Latent CLUB"
theme = "hugo-material-docs"
metadataformat = "yaml"

canonifyurls = true
# Enable Google Analytics by entering your tracking id
googleAnalytics = "UA-91393131-1"

[params]
	# General information
	# author = ""
	description = "주제별 커뮤니티 게시글 모음"
	# copyright = "Released under the MIT license"
	disqusShortname = "latent-club"
	# Repository
	# provider = "GitHub"
	# repo_url = "https://github.com/digitalcraftsman/hugo-material-docs"

	version = "2.0"
	logo = "/images/logo.png"
	favicon = ""

	permalink = "#"

	# Custom assets
	custom_css = []
	custom_js  = []

	# Syntax highlighting theme
	highlight_css  = ""

	[params.palette]
    	primary = "indigo"
    	accent  = "blue"

    [params.font]
    	text = "Ubuntu"
    	code = "Ubuntu Mono"


[social]
	twitter = ""
	github  = ""
	email   = "latent.info@gmail.com"


[[menu.main]]
	name   = "Intro"
	url    = "/"
	weight = 0


[[menu.main]]
	name   = "부동산"
	url    = "estate/"
	weight = 10

[[menu.main]]
	name   = "주식"
	url    = "stock/"
	weight = 20

[[menu.main]]
	name   = "경제"
	url    = "economy/"
	weight = 30

[[menu.main]]
	name   = "찌라시"
	url    = "tabloid/"
	weight = 40


[[menu.main]]
	name   = "가상화폐"
	url    = "coin/"
	weight = 50


[[menu.main]]
	name   = "트윗/페북"
	url    = "tweet/"
	weight = 60


[[menu.main]]
	name   = "About"
	url    = "about/"
	weight = 70


[[menu.main]]
	name   = "Board"
	url    = "board/"
	weight = 900


[blackfriday]
	smartypants	= true
	fractions = true
	smartDashes = true
	plainIDAnchors = true
